name: Package with pyinstaller and add to release

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    pyinstaller-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: PyInstaller Action
              id: pyinstall
              uses: JackMcKew/pyinstaller-action-windows@main
              with:
                path: .
            - name: Upload Release
              uses: AButler/upload-release-assets@v3.0
              with:
                files: dist/windows/server-update.exe
                repo-token: ${{ secrets.GITHUB_TOKEN }}
  