name: Package with pyinstaller and add to release

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    pyinstaller-build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: PyInstaller Action
              id: pyinstall
              uses: JackMcKew/pyinstaller-action-windows@main
              with:
                path: .
            - name: Upload Release
              uses: softprops/action-gh-release@v2
              with:
                files: "dist/server_update.exe"