name: Package with pyinstaller and add to release

on:
    workflow_dispatch:
    release:
        types: [published]

jobs:
    pyinstaller-build:
        runs-on: windows-latest
        steps:
            - name: PyInstaller Action
              id: pyinstall
              uses: Martin005/pyinstaller-action@v1.2.0
              with:
                spec: server_update.py
                exe_path: dist
                options: --onefile, --name "server_update"
            - name: Upload Release
              uses: AButler/upload-release-assets@v3.0
              with:
                files: "dist/server_update.exe"
                repo-token: ${{ secrets.GITHUB_TOKEN }}
